"""Model construction, registry, and leakage-safe runner utilities."""

from anaemia_ml.modeling.checkpoints import (
    CHECKPOINT_VERSION,
    CheckpointError,
    CheckpointIdentityError,
    CheckpointSnapshot,
    ExperimentIdentity,
    build_experiment_identity,
    empty_checkpoint,
    fingerprint_json,
    load_checkpoint,
    save_outer_fold_checkpoint,
)
from anaemia_ml.modeling.imbalance import (
    DEFAULT_CLASSES,
    FoldSafeClassWeightClassifier,
    ImbalanceError,
    ImbalanceSettings,
    SMOTENCSpec,
    balanced_class_weights,
    balanced_sample_weights,
    build_primary_imbalance_classifier,
    imbalance_settings,
    make_smotenc_spec,
    smotenc_categorical_indices,
    smotenc_sampling_targets,
)
from anaemia_ml.modeling.nested_cv import (
    CandidateScore,
    MetricAggregate,
    NestedCVError,
    NestedCVReport,
    OuterFoldResult,
    default_parameter_candidates,
    run_grouped_nested_cv,
)
from anaemia_ml.modeling.registry import (
    ModelDependencyError,
    ModelRegistryError,
    ModelSpec,
    build_estimator,
    model_spec,
    registered_models,
)
from anaemia_ml.modeling.runner import (
    DEFAULT_MODEL_NAMES,
    ModelRun,
    RunnerError,
    compare_models,
    fit_evaluate_model,
)
from anaemia_ml.modeling.search_space import (
    SearchSpaceError,
    load_search_space,
    search_space_fingerprint,
    suggest_parameters,
    validate_search_space,
)
from anaemia_ml.modeling.tuning import (
    OptunaDependencyError,
    TuningError,
    TuningResult,
    tune_parameters,
)

__all__ = [
    "CHECKPOINT_VERSION",
    "DEFAULT_CLASSES",
    "DEFAULT_MODEL_NAMES",
    "CandidateScore",
    "CheckpointError",
    "CheckpointIdentityError",
    "CheckpointSnapshot",
    "ExperimentIdentity",
    "FoldSafeClassWeightClassifier",
    "ImbalanceError",
    "ImbalanceSettings",
    "MetricAggregate",
    "ModelDependencyError",
    "ModelRegistryError",
    "ModelRun",
    "ModelSpec",
    "NestedCVError",
    "NestedCVReport",
    "OptunaDependencyError",
    "OuterFoldResult",
    "RunnerError",
    "SMOTENCSpec",
    "SearchSpaceError",
    "TuningError",
    "TuningResult",
    "balanced_class_weights",
    "balanced_sample_weights",
    "build_estimator",
    "build_experiment_identity",
    "build_primary_imbalance_classifier",
    "compare_models",
    "default_parameter_candidates",
    "empty_checkpoint",
    "fingerprint_json",
    "fit_evaluate_model",
    "imbalance_settings",
    "load_checkpoint",
    "load_search_space",
    "make_smotenc_spec",
    "model_spec",
    "registered_models",
    "run_grouped_nested_cv",
    "save_outer_fold_checkpoint",
    "search_space_fingerprint",
    "smotenc_categorical_indices",
    "smotenc_sampling_targets",
    "suggest_parameters",
    "tune_parameters",
    "validate_search_space",
]
